service: booking-api

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:AWS_PROFILE}
  region: ${env:REGION}
  role: ${env:AWS_LAMBDA_ROLE_ARN}

package:
  individually: true

plugins:
  - serverless-dotenv-plugin

functions:
  createBooking:
    handler: src/handlers/createBooking/index.handler
    events:
      - http:
          path: bookings
          method: post
          cors: true

  getBooking:
    handler: src/handlers/getBooking/index.handler
    events:
      - http:
          path: bookings/{id}
          method: get
          cors: true

  updateBooking:
    handler: src/handlers/updateBooking/index.handler
    events:
      - http:
          path: bookings/{id}
          method: put
          cors: true

  deleteBooking:
    handler: src/handlers/deleteBooking/index.handler
    events:
      - http:
          path: bookings/{id}
          method: delete
          cors: true
