service: booking-api

provider:
  name: aws
  runtime: nodejs20.x
  profile: ${env:AWS_PROFILE}       # Use profil from .env
  region: ${env:REGION}             # Use region from .env
  role: ${env:AWS_LAMBDA_ROLE_ARN}  # Use IAM-role from .env

package:
  individually: true

plugins:
  - serverless-dotenv-plugin

functions:
  hello:
    handler: handler.hello
    environment:                
      DYNAMODB_TABLE_NAME: ${env:DYNAMODB_TABLE_NAME}
    events:
      - http:
          path: hello
          method: get
